### ISSUE TITLE
It seems this package is not working on Unity 2019.4

### ISSUE THREAD

**Issue by ailuropoda0** [Prastiwar/UnitySerializedDictionary#2]
- [x] I've read [cotributing file](https://github.com/Prastiwar/RepositoryTemplate/tree/master/.github/CONTRIBUTING.md).
### **Clear and concise description of problem**

In my 2019.4.2f1 Unity Editor, the keys and values of serialized dictionaries are not shown like the below picture.

![Capture](https://user-images.githubusercontent.com/22828233/105115038-76277f80-5b0b-11eb-9da2-278492754462.PNG)

**Comment by Prastiwar** [comment]
Hey, thanks for letting me know.
I'm not up to date with Unity and it seems they changes something with property drawer behaviour probably, but then, I guess there would be some warnings or errors in script. I don't even have Unity on my PC so I won't really fix it, but if you have some experience you can debug these scripts and maybe fix it, then feel free to make a pull request :)

**Comment by Prastiwar** [comment]
Fixed it :)
