### ISSUE TITLE
Only part of Dictionary gets Serialized

### ISSUE THREAD

**Issue by Karottenrambo** [Prastiwar/UnitySerializedDictionary#6]
- [x] I've read [cotributing file](https://github.com/Prastiwar/RepositoryTemplate/tree/master/.github/CONTRIBUTING.md).
### **Clear and concise description of bug**
I encountered a wired issue on where only the first items that are added to the dictionary, are actually serialized using JsonUtility.

When I try adding subsequent items to the same dictionary, they show up correctly in the dict and I can work with them, however they get ignored when serializing it to an JSON.

### **Error information(log)**
no errors show

### **How to reproduce**
In Start() I init the Dict:

        intStringDict = new UDictionaryIntString();

On buttonpress i simply add an item and then log out its contents:

        intStringDict.TryAdd(Random.Range(0, 2000), Random.Range(0, 2000).ToString());

        string jsonintdict = JsonUtility.ToJson(intStringDict, true);

        foreach (var item in intStringDict)
        {
            Debug.Log("item values: " + item.Value);
        }
        Debug.Log(" json contains:" + jsonintdict);

on the first button press everything works fine, but on the end time adding an item and serializing it, only the first items gets serialized.

check the screenshot, this shows the dictionary on the 2nd time adding an item. "keys" correctly contains 2 values, however "m_keys" contains only one value, and only this one gets serialized.

### **Screenshots**
![keys](https://user-images.githubusercontent.com/17185301/187094976-db05dfa8-16a5-418d-b8f8-7ea7f24b40fa.png)
### **Evironment**
Unity 2021.3.8, newest release of [UnitySerializedDictionary](https://github.com/Prastiwar/UnitySerializedDictionary)

**Comment by Karottenrambo** [comment]
edit:
this added length check in UDictionary.cs fixed the issue for me:

        void ISerializationCallbackReceiver.OnBeforeSerialize()
        {
            if (m_keys == null || m_keys.Length != Keys.Count)
            {
                m_keys = Keys.ToArray();
                m_values = Values.ToArray();
            }
        }

**Comment by Prastiwar** [comment]
Hello @Karottenrambo 
I want to thank you for submitting this issue and apologize for late response - I don't have time to maintain this repository on my own (and I don't use Unity anymore) and would like to rely on community pull requests.

I don't remember why the null check was put there and your solution is not entirely accurate - there is one more edge case when m_keys can have the same count as Keys, but values will not be the same.

Can I ask you to verify if you have any issues without the whole if check?
```cs
    void ISerializationCallbackReceiver.OnBeforeSerialize()
    {
        m_keys = Keys.ToArray();
        m_values = Values.ToArray();
    }
```

**Comment by Karottenrambo** [comment]
Thanks for the response, yeah seems to be working fine without the if check.

**Comment by Prastiwar** [comment]
Thanks for your confirmation, I really appreciate the contribution 😄
